# Generated by Django 4.1.5 on 2023-01-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_audio_audio2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audio2',
        ),
    ]
