# Generated by Django 4.1.5 on 2023-01-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vocalizacion',
        ),
    ]
