# Generated by Django 4.1.5 on 2023-01-10 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_vocalizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
