# Generated by Django 4.1.5 on 2023-01-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_media_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='timestamp',
            field=models.CharField(max_length=100),
        ),
    ]
