# Generated by Django 4.1.5 on 2023-01-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_media_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intensidad',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='intensidad',
            name='usuario',
        ),
        migrations.AddField(
            model_name='intensidad',
            name='bpm',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intensidad',
            name='tiempo',
            field=models.CharField(default=1111, max_length=100),
            preserve_default=False,
        ),
    ]
