# Generated by Django 4.1.5 on 2023-01-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_intensidad_audio_remove_intensidad_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='idterapia',
            field=models.CharField(default=111, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='idusuario',
            field=models.CharField(default=11111111, max_length=100),
            preserve_default=False,
        ),
    ]
