# Generated by Django 4.1.5 on 2023-01-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_bpm_intensidad_idusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocalpalabras',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='vocaltexto',
            name='usuario',
        ),
        migrations.AddField(
            model_name='intensidad',
            name='bpm',
            field=models.CharField(default=1111, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Memorice',
        ),
        migrations.DeleteModel(
            name='VocalPalabras',
        ),
        migrations.DeleteModel(
            name='VocalTexto',
        ),
    ]
