# Generated by Django 4.1.5 on 2023-01-12 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_intensidad_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intensidad',
            old_name='id',
            new_name='idusuario',
        ),
    ]
