# Generated by Django 4.1.5 on 2023-01-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_media_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='audio',
            field=models.FileField(upload_to='media/vocalizacion'),
        ),
    ]
