# Generated by Django 4.1.5 on 2023-01-17 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_media_audio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Intensidad',
            new_name='Parametros',
        ),
    ]
