# Generated by Django 4.1.5 on 2023-01-17 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_intensidad_parametros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametros',
            name='bpm',
        ),
    ]
