# Generated by Django 4.1.5 on 2023-01-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_parametros_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametros',
            old_name='tiempo',
            new_name='tiempoIntensidad',
        ),
        migrations.AddField(
            model_name='parametros',
            name='tiempoVocalizacion',
            field=models.CharField(default=111111111, max_length=100),
            preserve_default=False,
        ),
    ]
