# Generated by Django 4.1.5 on 2023-01-20 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_tiempo_parametros_tiempointensidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_usuario', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='Apellido',
            new_name='diabetes',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='Edad',
            new_name='hipertencion',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='Nombre',
            new_name='rut_paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='Sexo',
            new_name='telegram_paciente',
        ),
        migrations.AlterField(
            model_name='media',
            name='idPaciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente'),
        ),
        migrations.CreateModel(
            name='Fonoaudiologo',
            fields=[
                ('id_fonoaudiologo', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut_fonoaudilogo', models.CharField(max_length=100)),
                ('institucion_id', models.CharField(max_length=100)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.authuser')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id_familiar', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut_familiar', models.CharField(max_length=100)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.authuser')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.authuser'),
            preserve_default=False,
        ),
    ]
