# Generated by Django 4.1.5 on 2023-01-20 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_authuser_tipousuario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
    ]
