# Generated by Django 4.1.5 on 2023-02-25 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudiosCoeficientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=100)),
                ('F0', models.CharField(max_length=100)),
                ('F1', models.CharField(max_length=100)),
                ('F2', models.CharField(max_length=100)),
                ('F3', models.CharField(max_length=100)),
                ('F4', models.CharField(max_length=100)),
                ('Intensidad', models.CharField(max_length=100)),
                ('HNR', models.CharField(max_length=100)),
                ('Local_Jitter', models.CharField(max_length=100)),
                ('Local_Absolute_Jitter', models.CharField(max_length=100)),
                ('Rap_Jitter', models.CharField(max_length=100)),
                ('ppq5_Jitter', models.CharField(max_length=100)),
                ('ddp_Jitter', models.CharField(max_length=100)),
                ('Local_Shimmer', models.CharField(max_length=100)),
                ('Local_db_Shimmer', models.CharField(max_length=100)),
                ('apq3_Shimmer', models.CharField(max_length=100)),
                ('aqpq5_Shimmer', models.CharField(max_length=100)),
                ('apq11_Shimmer', models.CharField(max_length=100)),
                ('idusuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
