# Generated by Django 4.1.5 on 2023-01-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audio',
            new_name='Audio2',
        ),
    ]
