# Generated by Django 4.1.5 on 2023-02-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_audioscoeficientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rasati',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_fonoaudilogo', models.CharField(max_length=100)),
                ('id_paciente', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=100)),
                ('R', models.CharField(max_length=100)),
                ('S', models.CharField(max_length=100)),
                ('A', models.CharField(max_length=100)),
                ('T', models.CharField(max_length=100)),
                ('I', models.CharField(max_length=100)),
                ('Comentario', models.CharField(max_length=100)),
            ],
        ),
    ]
