# Generated by Django 4.1.5 on 2023-02-02 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_app_documento_diabetes_hipertension_vocalizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipoaudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_usuario', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_usuario',
            field=models.ForeignKey(limit_choices_to={'id_tipo_user': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profesional_paciente',
            name='tipo_profesional',
            field=models.ForeignKey(limit_choices_to={'id_tipo_user': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
