# Generated by Django 4.1.5 on 2023-01-23 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id_institucion', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_institucion', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id_familiar', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut_familiar', models.CharField(max_length=100)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
