# Generated by Django 4.1.5 on 2023-02-03 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tipoaudio_alter_paciente_id_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonoaudilogos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=100)),
                ('NombreCompleto', models.CharField(max_length=100)),
                ('Registro', models.CharField(max_length=100)),
                ('RegionLaboral', models.CharField(max_length=100)),
                ('TituloProfesional', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='profesional_paciente',
            name='tipo_profesional',
            field=models.ForeignKey(limit_choices_to=models.Q(('id_tipo_user', 1), ('id_tipo_user', 2), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
