# Generated by Django 4.1.5 on 2023-01-23 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_institucion_familiar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional_salud',
            fields=[
                ('id_profesional', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut_profesional', models.CharField(max_length=100)),
                ('institucion_id', models.CharField(max_length=100)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
