# Generated by Django 4.1.5 on 2023-01-23 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profesional_salud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional_salud',
            name='institucion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.institucion'),
        ),
    ]
