# Generated by Django 4.1.5 on 2023-02-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_fonoaudilogos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonoaudilogos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
