# Generated by Django 4.1.5 on 2023-01-23 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_profesional_salud_institucion_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional_Paciente',
            fields=[
                ('id_prof_paci', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente')),
                ('id_profesional_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profesional_salud')),
            ],
        ),
    ]
