# Generated by Django 4.1.5 on 2023-02-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_preregistro_comuna'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preregistro',
            old_name='password',
            new_name='telefono',
        ),
        migrations.AlterField(
            model_name='preregistro',
            name='tipo_user',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
