# Generated by Django 4.1.5 on 2023-01-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_media_idterapia_media_idusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intensidad',
            old_name='bpm',
            new_name='idusuario',
        ),
    ]
