# Generated by Django 4.1.5 on 2023-01-23 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_parametros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar_paciente',
            fields=[
                ('id_fam_pac', models.BigAutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(max_length=100)),
                ('id_familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.familiar')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente')),
            ],
        ),
    ]
