# Generated by Django 4.1.5 on 2023-01-23 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_familiar_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='idPaciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.paciente'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='familiar_paciente',
            name='id_familiar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.familiar'),
        ),
        migrations.AlterField(
            model_name='familiar_paciente',
            name='id_paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.paciente'),
        ),
        migrations.AlterField(
            model_name='profesional_paciente',
            name='id_paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.paciente'),
        ),
        migrations.AlterField(
            model_name='profesional_paciente',
            name='id_profesional_salud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.profesional_salud'),
        ),
        migrations.AlterField(
            model_name='profesional_salud',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profesional_salud',
            name='institucion_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.institucion'),
        ),
    ]
