# Generated by Django 4.1.5 on 2023-02-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_preregistro_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonoaudilogos',
            name='preregistrado',
            field=models.IntegerField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
