# Generated by Django 4.1.5 on 2023-02-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_fonoaudilogos_preregistrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonoaudilogos',
            name='preregistrado',
            field=models.CharField(max_length=100),
        ),
    ]
