# Generated by Django 4.1.5 on 2023-01-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_vocalpalabras_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idPaciente', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Edad', models.CharField(max_length=100)),
                ('Sexo', models.CharField(max_length=100)),
                ('Observacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='intensidad',
            name='idusuario',
        ),
        migrations.RemoveField(
            model_name='media',
            name='idterapia',
        ),
        migrations.RemoveField(
            model_name='media',
            name='idusuario',
        ),
    ]
