# Generated by Django 4.1.5 on 2023-01-23 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_audio_idpaciente_alter_familiar_id_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='idPaciente',
        ),
        migrations.AddField(
            model_name='audio',
            name='idusuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
