# Generated by Django 4.1.5 on 2023-01-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_id_intensidad_idusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='audio',
            field=models.FileField(upload_to='vocalizacion'),
        ),
    ]
