# Generated by Django 4.1.5 on 2023-01-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_parametros_bpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametros',
            name='Descripcion',
            field=models.CharField(default=1111111, max_length=100),
            preserve_default=False,
        ),
    ]
